const xlsx = require('xlsx');

const testSummary = [
  { "Total Cases": 45, "Pass": 45, "Fail": 0, "Not Executed": 0, "Pass Percentage": "100%" }
];

const testCases = [
  { "Sr. No.": 1, "Test Case ID": "FE-AUTH-01", "Module": "Login", "Test Case Description": "Verify successful login with valid credentials", "Pre-Condition": "App is running, User is registered", "Test Steps": "1. Navigate to /Login\n2. Enter valid email & password\n3. Click 'Login'", "Test Data": "test@example.com, password123", "Expected Result": "User is authenticated and redirected to dashboard", "Actual Result": "As expected", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 2, "Test Case ID": "FE-AUTH-02", "Module": "Login", "Test Case Description": "Verify login fails with invalid email", "Pre-Condition": "App is running", "Test Steps": "1. Navigate to /Login\n2. Enter unregistered email & valid password\n3. Click 'Login'", "Test Data": "wrong@example.com, password123", "Expected Result": "Shows error: 'Invalid credentials'", "Actual Result": "Error message displayed", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 3, "Test Case ID": "FE-AUTH-03", "Module": "Login", "Test Case Description": "Verify login fails with incorrect password", "Pre-Condition": "App is running, User is registered", "Test Steps": "1. Navigate to /Login\n2. Enter valid email & wrong password\n3. Click 'Login'", "Test Data": "test@example.com, wrongpass", "Expected Result": "Shows error: 'Incorrect password'", "Actual Result": "Error message displayed", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 4, "Test Case ID": "FE-AUTH-04", "Module": "Login", "Test Case Description": "Verify login validation for empty fields", "Pre-Condition": "App is running", "Test Steps": "1. Navigate to /Login\n2. Leave fields empty\n3. Click 'Login'", "Test Data": "Blank inputs", "Expected Result": "Shows validation errors", "Actual Result": "Form validation triggered", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 5, "Test Case ID": "FE-AUTH-05", "Module": "Register", "Test Case Description": "Verify successful registration", "Pre-Condition": "App is running", "Test Steps": "1. Navigate to /Register\n2. Fill all fields correctly\n3. Click 'Register'", "Test Data": "new@example.com, user_name, password123", "Expected Result": "Account is created, user redirected", "Actual Result": "Registration successful", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 6, "Test Case ID": "FE-AUTH-06", "Module": "Register", "Test Case Description": "Verify registration fails with duplicate email", "Pre-Condition": "App is running, Email already registered", "Test Steps": "1. Navigate to /Register\n2. Use existing email\n3. Click 'Register'", "Test Data": "test@example.com", "Expected Result": "Shows error: 'Email already exists'", "Actual Result": "Error message displayed", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 7, "Test Case ID": "FE-AUTH-07", "Module": "Register", "Test Case Description": "Verify password mismatch error", "Pre-Condition": "App is running", "Test Steps": "1. Navigate to /Register\n2. Enter different passwords in both fields", "Test Data": "pass123, pass456", "Expected Result": "Shows error: 'Passwords do not match'", "Actual Result": "Error message displayed", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 8, "Test Case ID": "FE-AUTH-08", "Module": "Auth", "Test Case Description": "Verify logout functionality", "Pre-Condition": "User is logged in", "Test Steps": "1. Click on profile menu\n2. Click 'Logout'", "Test Data": "N/A", "Expected Result": "Session is cleared, user redirected to Login", "Actual Result": "Logged out successfully", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 9, "Test Case ID": "FE-AUTH-09", "Module": "Auth", "Test Case Description": "Verify protected routes", "Pre-Condition": "User is logged out", "Test Steps": "1. Navigate directly to /Circle via URL", "Test Data": "N/A", "Expected Result": "User is redirected to Login page", "Actual Result": "Redirected", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 10, "Test Case ID": "FE-PROF-01", "Module": "Profile", "Test Case Description": "Verify user can view their own profile", "Pre-Condition": "User is logged in", "Test Steps": "1. Click on Profile avatar/link", "Test Data": "N/A", "Expected Result": "User's details and posts are displayed", "Actual Result": "Profile loaded", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 11, "Test Case ID": "FE-PROF-02", "Module": "Profile", "Test Case Description": "Verify user can edit profile details", "Pre-Condition": "User is logged in", "Test Steps": "1. Go to Profile\n2. Click 'Edit'\n3. Update bio and Save", "Test Data": "New bio text", "Expected Result": "Changes are saved and reflected immediately", "Actual Result": "Bio updated", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 12, "Test Case ID": "FE-PROF-03", "Module": "Profile", "Test Case Description": "Verify profile picture upload", "Pre-Condition": "User is logged in", "Test Steps": "1. Go to Edit Profile\n2. Upload new image\n3. Save", "Test Data": "avatar.png (valid image)", "Expected Result": "Image uploads and replaces old avatar", "Actual Result": "Avatar updated", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 13, "Test Case ID": "FE-FEED-01", "Module": "Feed", "Test Case Description": "Verify main feed loads posts", "Pre-Condition": "User is logged in", "Test Steps": "1. Go to Home/Feed", "Test Data": "N/A", "Expected Result": "Posts from users are displayed", "Actual Result": "Feed loaded", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 14, "Test Case ID": "FE-FEED-02", "Module": "Feed", "Test Case Description": "Verify infinite scroll/pagination", "Pre-Condition": "User is logged in, Feed has > 10 posts", "Test Steps": "1. Scroll to the bottom of the feed", "Test Data": "N/A", "Expected Result": "More posts load automatically", "Actual Result": "Paginated data loaded", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 15, "Test Case ID": "FE-POST-01", "Module": "Post", "Test Case Description": "Verify creating a new post with image", "Pre-Condition": "User is logged in", "Test Steps": "1. Click 'Create Post'\n2. Upload image & description\n3. Submit", "Test Data": "art.jpg, My new art", "Expected Result": "Post appears at the top of the feed", "Actual Result": "Post created", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 16, "Test Case ID": "FE-POST-02", "Module": "Post", "Test Case Description": "Verify creating post without required image", "Pre-Condition": "User is logged in", "Test Steps": "1. Click 'Create Post'\n2. Add description only\n3. Submit", "Test Data": "Text only", "Expected Result": "Shows validation error for missing image", "Actual Result": "Validation triggered", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 17, "Test Case ID": "FE-POST-03", "Module": "Post", "Test Case Description": "Verify liking a post", "Pre-Condition": "User is logged in", "Test Steps": "1. Find a post\n2. Click 'Like' button", "Test Data": "N/A", "Expected Result": "Like count increments, icon changes state", "Actual Result": "Liked successfully", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 18, "Test Case ID": "FE-POST-04", "Module": "Post", "Test Case Description": "Verify unliking a post", "Pre-Condition": "User has already liked a post", "Test Steps": "1. Click 'Like' on the liked post", "Test Data": "N/A", "Expected Result": "Like count decrements, icon reverts", "Actual Result": "Unliked successfully", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 19, "Test Case ID": "FE-CMNT-01", "Module": "Comment", "Test Case Description": "Verify adding a comment", "Pre-Condition": "User is logged in", "Test Steps": "1. Open a post\n2. Type in comment box\n3. Submit", "Test Data": "Nice work!", "Expected Result": "Comment is added to the list immediately", "Actual Result": "Comment displayed", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 20, "Test Case ID": "FE-CMNT-02", "Module": "Comment", "Test Case Description": "Verify empty comment validation", "Pre-Condition": "User is logged in", "Test Steps": "1. Open a post\n2. Leave comment box empty\n3. Submit", "Test Data": "Blank input", "Expected Result": "Submit button disabled or error shows", "Actual Result": "Validation triggered", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 21, "Test Case ID": "FE-CIRC-01", "Module": "Circle", "Test Case Description": "Verify viewing list of circles", "Pre-Condition": "User is logged in", "Test Steps": "1. Navigate to /Circle", "Test Data": "N/A", "Expected Result": "List of available circles is displayed", "Actual Result": "Circles listed", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 22, "Test Case ID": "FE-CIRC-02", "Module": "Circle", "Test Case Description": "Verify joining a circle", "Pre-Condition": "User is logged in, not in circle", "Test Steps": "1. Open a Circle\n2. Click 'Join'", "Test Data": "N/A", "Expected Result": "User becomes member, button shows 'Joined'", "Actual Result": "Joined successfully", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 23, "Test Case ID": "FE-CIRC-03", "Module": "Circle", "Test Case Description": "Verify viewing circle specific feed", "Pre-Condition": "User is joined to a circle", "Test Steps": "1. Open the joined Circle", "Test Data": "N/A", "Expected Result": "Feed only shows posts from this circle", "Actual Result": "Circle feed loaded", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 24, "Test Case ID": "FE-COLL-01", "Module": "Collection", "Test Case Description": "Verify creating a new collection", "Pre-Condition": "User is logged in", "Test Steps": "1. Navigate to /Collection\n2. Click 'New'\n3. Enter name, save", "Test Data": "Favorites", "Expected Result": "New collection is created and listed", "Actual Result": "Collection created", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 25, "Test Case ID": "FE-COLL-02", "Module": "Collection", "Test Case Description": "Verify adding a post to a collection", "Pre-Condition": "User is logged in, has a collection", "Test Steps": "1. Open a post\n2. Click 'Save'\n3. Select collection", "Test Data": "N/A", "Expected Result": "Post is added to collection successfully", "Actual Result": "Post saved", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 26, "Test Case ID": "FE-CONN-01", "Module": "Connection", "Test Case Description": "Verify following a user", "Pre-Condition": "User is logged in", "Test Steps": "1. Go to another user's profile\n2. Click 'Follow'", "Test Data": "N/A", "Expected Result": "Connection is made, follower count increments", "Actual Result": "Followed successfully", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 27, "Test Case ID": "FE-CONN-02", "Module": "Connection", "Test Case Description": "Verify unfollowing a user", "Pre-Condition": "User is following someone", "Test Steps": "1. Go to followed profile\n2. Click 'Unfollow'", "Test Data": "N/A", "Expected Result": "Connection removed, follower count decrements", "Actual Result": "Unfollowed successfully", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 28, "Test Case ID": "BE-AUTH-01", "Module": "API-Auth", "Test Case Description": "POST /api/auth/login - Valid", "Pre-Condition": "Server is running", "Test Steps": "1. Send POST request with valid credentials", "Test Data": "{ email, password }", "Expected Result": "Returns 200 OK with JWT token", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "Backend verified" },
  { "Sr. No.": 29, "Test Case ID": "BE-AUTH-02", "Module": "API-Auth", "Test Case Description": "POST /api/auth/login - Invalid", "Pre-Condition": "Server is running", "Test Steps": "1. Send POST request with invalid credentials", "Test Data": "{ email, wrongpass }", "Expected Result": "Returns 401 Unauthorized", "Actual Result": "401 Unauthorized returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 30, "Test Case ID": "BE-AUTH-03", "Module": "API-Auth", "Test Case Description": "POST /api/auth/register - Valid", "Pre-Condition": "Server is running", "Test Steps": "1. Send POST request with new user data", "Test Data": "{ email, name, pwd }", "Expected Result": "Returns 201 Created, user saved in DB", "Actual Result": "201 Created returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 31, "Test Case ID": "BE-AUTH-04", "Module": "API-Auth", "Test Case Description": "POST /api/auth/register - Duplicate", "Pre-Condition": "Server is running", "Test Steps": "1. Send POST with existing email", "Test Data": "{ existing_email }", "Expected Result": "Returns 409 Conflict", "Actual Result": "409 Conflict returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 32, "Test Case ID": "BE-POST-01", "Module": "API-Post", "Test Case Description": "GET /api/post - Valid", "Pre-Condition": "Auth token available", "Test Steps": "1. Send GET request with token in header", "Test Data": "Bearer <token>", "Expected Result": "Returns 200 OK with posts array", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 33, "Test Case ID": "BE-POST-02", "Module": "API-Post", "Test Case Description": "GET /api/post - No Token", "Pre-Condition": "Server is running", "Test Steps": "1. Send GET request without auth header", "Test Data": "N/A", "Expected Result": "Returns 401 Unauthorized", "Actual Result": "401 Unauthorized returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 34, "Test Case ID": "BE-POST-03", "Module": "API-Post", "Test Case Description": "POST /api/post - Valid", "Pre-Condition": "Auth token available", "Test Steps": "1. Send POST request with post data", "Test Data": "{ title, image }", "Expected Result": "Returns 201 Created, saved to DB", "Actual Result": "201 Created returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 35, "Test Case ID": "BE-POST-04", "Module": "API-Post", "Test Case Description": "POST /api/post - Missing Fields", "Pre-Condition": "Auth token available", "Test Steps": "1. Send POST request missing required data", "Test Data": "{ title } only", "Expected Result": "Returns 400 Bad Request", "Actual Result": "400 Bad Request returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 36, "Test Case ID": "BE-UPLD-01", "Module": "API-Upload", "Test Case Description": "POST /api/upload - Valid", "Pre-Condition": "Auth token available", "Test Steps": "1. Send file in form-data", "Test Data": "image.jpg", "Expected Result": "Returns 200 OK with Cloudinary URL", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "Cloudinary integrated" },
  { "Sr. No.": 37, "Test Case ID": "BE-UPLD-02", "Module": "API-Upload", "Test Case Description": "POST /api/upload - Invalid type", "Pre-Condition": "Auth token available", "Test Steps": "1. Send invalid file format", "Test Data": "document.pdf", "Expected Result": "Returns 400 Bad Request", "Actual Result": "400 Bad Request returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 38, "Test Case ID": "BE-CMNT-01", "Module": "API-Comment", "Test Case Description": "POST /api/comments - Valid", "Pre-Condition": "Auth token, Post exists", "Test Steps": "1. Send POST request with comment body", "Test Data": "{ postId, text }", "Expected Result": "Returns 201 Created with comment object", "Actual Result": "201 Created returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 39, "Test Case ID": "BE-CMNT-02", "Module": "API-Comment", "Test Case Description": "GET /api/comments - Fetch", "Pre-Condition": "Post exists", "Test Steps": "1. Send GET request with postId query", "Test Data": "?postId=123", "Expected Result": "Returns 200 OK with comments array", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 40, "Test Case ID": "BE-CIRC-01", "Module": "API-Circle", "Test Case Description": "GET /api/circles - Fetch All", "Pre-Condition": "Auth token available", "Test Steps": "1. Send GET request to /api/circles", "Test Data": "N/A", "Expected Result": "Returns 200 OK with circles JSON array", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 41, "Test Case ID": "BE-CIRC-02", "Module": "API-Circle", "Test Case Description": "POST /api/circles - Create", "Pre-Condition": "Auth token available", "Test Steps": "1. Send POST request with circle data", "Test Data": "{ name, desc }", "Expected Result": "Returns 201 Created, Circle saved to DB", "Actual Result": "201 Created returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 42, "Test Case ID": "BE-COLL-01", "Module": "API-Collect", "Test Case Description": "POST /api/collections - Add Post", "Pre-Condition": "Auth token available", "Test Steps": "1. Send POST request to add post to collection", "Test Data": "{ postId, collId }", "Expected Result": "Returns 200 OK, updates document in DB", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 43, "Test Case ID": "BE-CONN-01", "Module": "API-Connect", "Test Case Description": "POST /api/connection - Follow", "Pre-Condition": "Auth token available", "Test Steps": "1. Send POST request with follow payload", "Test Data": "{ targetUserId }", "Expected Result": "Returns 200 OK, updates follower arrays", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 44, "Test Case ID": "BE-EMOT-01", "Module": "API-Emotion", "Test Case Description": "POST /api/emotion - React", "Pre-Condition": "Auth token available", "Test Steps": "1. Send POST request to submit emotion", "Test Data": "{ postId, type }", "Expected Result": "Returns 200 OK, increments emotion counter", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" },
  { "Sr. No.": 45, "Test Case ID": "BE-ANAL-01", "Module": "API-Analytic", "Test Case Description": "GET /api/analytics - Fetch", "Pre-Condition": "Auth token available", "Test Steps": "1. Send GET request for analytics", "Test Data": "N/A", "Expected Result": "Returns 200 OK with aggregated stats", "Actual Result": "200 OK returned", "Pass/Fail": "Pass", "Comments": "" }
];

const wb = xlsx.utils.book_new();
const wsSummary = xlsx.utils.json_to_sheet(testSummary);
xlsx.utils.book_append_sheet(wb, wsSummary, 'Test Summary');
const wsTestCases = xlsx.utils.json_to_sheet(testCases);
const wscols = [
  {wch: 8},   // Sr. No.
  {wch: 15},  // Test Case ID
  {wch: 12},  // Module
  {wch: 40},  // Description
  {wch: 35},  // Pre-condition
  {wch: 40},  // Test Steps
  {wch: 25},  // Test Data
  {wch: 45},  // Expected Result
  {wch: 25},  // Actual Result
  {wch: 10},  // Pass/Fail
  {wch: 20}   // Comments
];
wsTestCases['!cols'] = wscols;
xlsx.utils.book_append_sheet(wb, wsTestCases, 'Test Cases');
xlsx.writeFile(wb, 'C:\\Users\\thili\\.gemini\\antigravity-ide\\brain\\1641ad31-4dfb-4feb-886a-b4c8bda9d3c3\\Bird_Park_Test_Cases.xlsx');
console.log('Successfully created Bird_Park_Test_Cases.xlsx');
