import { Schema, model, models } from "mongoose";

const PostSchema = new Schema(
  {
    // ============================================================
    // AUTHOR
    // ============================================================

    author: {
      type: Schema.Types.ObjectId,
      ref: "Artist",
      required: true,
    },

    // ============================================================
    // POST TYPE
    // ============================================================

    type: {
      type: String,
      enum: ["art", "poem"],
      required: true,
    },

    // ============================================================
    // BASIC POST INFORMATION
    // ============================================================

    title: {
      type: String,
      required: true,
    },

    body: {
      type: String,
    },

    // ============================================================
    // CLOUDINARY MEDIA
    // Used mainly for artwork
    // ============================================================

    media: {
      url: {
        type: String,
      },

      publicId: {
        type: String,
      },

      type: {
        type: String,
        enum: ["image", "video"],
      },
    },

    // ============================================================
    // POEM STYLING
    // Only used when type = poem
    // ============================================================

    poemStyle: {
      fontFamily: {
        type: String,
      },

      fontSize: {
        type: String,
      },

      fontColor: {
        type: String,
      },

      backgroundColor: {
        type: String,
      },
    },

    // ============================================================
    // SOCIAL INTERACTIONS
    // ============================================================

    hearts: [
      {
        type: Schema.Types.ObjectId,
        ref: "Artist",
      },
    ],

    comments: [
      {
        type: Schema.Types.ObjectId,
        ref: "Comment",
      },
    ],

    // ============================================================
    // COLLECTION
    // ============================================================

    artCollection: {
      type: Schema.Types.ObjectId,
      ref: "artCollection",
      default: null,
    },

    // ============================================================
    // AI SEMANTIC ANALYSIS
    //
    // Works for BOTH:
    //      art
    //      poem
    //
    // Example:
    //
    // story:
    // "A person continues to hold onto a lost love..."
    //
    // cluster:
    // "Loss & absence"
    //
    // ============================================================

    semanticAnalysis: {
      story: {
        type: String,
        default: null,
      },

      cluster: {
        type: String,
        default: null,
      },

      // ==========================================================
      // MATCHING DATA
      // ==========================================================

      matching: {
        cluster: {
          type: String,
          default: null,
        },

        // Semantic text generated by the AI.
        //
        // This is NOT the vector.
        // It will be passed to the embedding model.
        embedText: {
          type: String,
          default: null,
        },

        // ========================================================
        // ACTUAL EMBEDDING VECTOR
        //
        // Example:
        //
        // [0.123, -0.392, 0.771, ...]
        //
        // This will be populated after the embedding model
        // processes embedText.
        // ========================================================

        embedding: {
          type: [Number],
          default: [],
        },
      },
    },

    // ============================================================
    // AI PROCESSING STATUS
    // ============================================================

    emotionAnalysis: {
      status: {
        type: String,

        enum: [
          "pending",
          "processing",
          "completed",
          "failed",
        ],

        default: "pending",
      },

      completedAt: {
        type: Date,
        default: null,
      },

      error: {
        type: String,
        default: null,
      },
    },

    // ============================================================
    // CIRCLE
    // ============================================================

    circle: {
      type: Schema.Types.ObjectId,
      ref: "Circle",
      default: null,
    },

    // ============================================================
    // ACTIVITY
    // ============================================================

    activity: {
      type: Schema.Types.ObjectId,
      ref: "SharedPromptActivity",
      default: null,
    },

    // ============================================================
    // VISIBILITY
    // ============================================================

    visibility: {
      type: String,

      enum: [
        "public",
        "circle",
      ],

      default: "public",
    },
  },

  {
    timestamps: true,
  }
);

const Post =
  models.Post ||
  model("Post", PostSchema);

export default Post;